// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo9YOKBLbvPUUuIXA8w6DPNWWWB8k7ndI',
    appId: '1:911499303394:android:5967b5079e7ae5b7bb01bb',
    messagingSenderId: '911499303394',
    projectId: 'parkingapplication-e49be',
    databaseURL: 'https://parkingapplication-e49be-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'parkingapplication-e49be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7C0G2eQGKOwWbnhgtfIr3E3NLIb520IU',
    appId: '1:911499303394:ios:148e223fcdef7860bb01bb',
    messagingSenderId: '911499303394',
    projectId: 'parkingapplication-e49be',
    databaseURL: 'https://parkingapplication-e49be-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'parkingapplication-e49be.appspot.com',
    androidClientId: '911499303394-0reino6nmgqfd0lqvf87p21b0lteh489.apps.googleusercontent.com',
    iosClientId: '911499303394-kfflklu4007h8moc2unvmmdtf2d7nqrk.apps.googleusercontent.com',
    iosBundleId: 'com.example.carParkingApplication',
  );
}
